server:
  port: 4551

management:
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: wa-task-configuration-template
